/**
 * NeedCharge Mobile
 * Mobile API for needcharge
 *
 *
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.app.interfaces.models.common

import com.google.gson.annotations.SerializedName


/**
 *
 * @param error
 */
data class ErrorModel(
    val code: Int = 0,
    @SerializedName("message")
    val error: String?,
    val message: List<String>?
)